# Generated by Django 5.2 on 2025-11-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_certifications_user_full_name_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
