# Generated by Django 5.2 on 2025-11-02 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_duplicate_applications"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("applicant", "job")},
        ),
    ]
