# Generated by Django 5.2.7 on 2025-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_application_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="resume",
        ),
        migrations.AddField(
            model_name="application",
            name="resume_content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
